name: Check Download Step

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Just
        run: sudo snap install --edge --classic just
      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          export PATH="$HOME/.local/bin:$PATH"
      - name: Run download step
        run: just download
